### ISSUE TITLE
[bug] edit - inventory items: validation popup is truncated

### ISSUE THREAD

**Issue by davide-alghi** [YetiForceCompany/YetiForceCRM#10546]
# 🐞 bug report
In all inventory entities, inventory items validation popup is truncated on insert error
Validation popup is closed inside a
```HTML
<td class="colName text-right fieldValue u-text-ellipsis">
```
with **overflow: hidden** (by **.u-text-ellipsis**)

### 🔥 How to trigger the error
![popuphidden](https://user-images.githubusercontent.com/48508691/58499965-7b3efa80-8181-11e9-91c0-90fffc1760c0.gif)

### 👎 Actual Behavior
validation popup is hidden

### 👍 Expected Behavior
validation popup must be visible

### 📷 Screenshot of configuration
[none]

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
[indipendent]

### 🌍  Your Environment 
[indipendent]

### ❓ Additional context
[none]

### :heavy_check_mark: Fix
into **/public_html/layouts/basic/styles/Main.css** add **.colName** class style
```CSS
   ...
   .inventoryItems .rowName .input-group {
      max-width: 400px; }
/* ===>> added next 2 lines */
   .colName {
      overflow: visible !important; }
   .inventoryItems tfoot td.hideTd {
      border-width: 0 0 1px 0;
      background: #fafafb; }
   ...
```
